### ISSUE TITLE
Quasi-Static calculation with PUT_SPRING()

### ISSUE THREAD

**Issue by nicolasmecamas** [tkoziara/solfec#66]
Hi Tomek,
I am currently working the castest of quasi-static with PUT_SPRING() (file: Test_QS_with_PUT_SPRING.py).
When launching this file, it generated the error that I put in the file Error_QS_with_PUT_SPRING.docx.
Could you please help me explain?
Thank you in advance,
Nicolas
 
[Error_QS_with_PUT_SPRING.docx](https://github.com/tkoziara/solfec/files/1047682/Error_QS_with_PUT_SPRING.docx)
[Test_QS_with_PUT_SPRING.py.docx](https://github.com/tkoziara/solfec/files/1047681/Test_QS_with_PUT_SPRING.py.docx)

**Comment by tkoziara** [comment]
Hi,
Thank you for spotting this; Please update solfec and try again:)
Tomek

**Comment by nicolasmecamas** [comment]
Hi Tomek,
I updated the newest version. It works for quasi-static simulation but not for MPI.
With mpi, it generates the same error like before.

Peter@linux:​/Works/Debugs/mpi/PUT_SPRING_Q​S$ mpirun -np 4 solfec-mpi PUT_SPRING_2_sphere-FEM_QUASI_​STATIC.py​

Traceback (most recent call last):

File "<string>", line 1, in <module>

File "PUT_SPRING_2_sphere-FEM_QUASI​_STATIC.py",​ line 53, in <module>

   PUT_SPRING (bod_Haut, bod_Haut.center, bod_Bas, bod_Bas.center, springfunc, (-0.5 , 0.5))

TypeError: 'body2' must be a tuple object

WARNING solfec.c: 295 => input parsing error

Traceback (most recent call last):

File "<string>", line 1, in <module>

File "PUT_SPRING_2_sphere-FEM_QUASI​_STATIC.py",​ line 53, in <module>

PUT_SPRING (bod_Haut, bod_Haut.center, bod_Bas, bod_Bas.center, springfunc, (-0.5 , 0.5))

TypeError: 'body2' must be a tuple object

WARNING solfec.c: 295 => input parsing error

Traceback (most recent call last):

File "<string>", line 1, in <module>

File "PUT_SPRING_2_sphere-FEM_QUASI​_STATIC.py",​ line 53, in <module>

   PUT_SPRING (bod_Haut, bod_Haut.center, bod_Bas, bod_Bas.center, springfunc, (-0.5 , 0.5))

TypeError: 'body2' must be a tuple object

WARNING solfec.c: 295 => input parsing error

**Comment by tkoziara** [comment]
:) OK -> can you attach: PUT_SPRING_2_sphere-FEM_QUASI_​STATIC.py​ ?
Thanks,
Tomek

**Comment by nicolasmecamas** [comment]
Here are you
Thanks,
Nicolas
[PUT_SPRING_2_sphere-RIG.py.docx](https://github.com/tkoziara/solfec/files/1064209/PUT_SPRING_2_sphere-RIG.py.docx)

**Comment by tkoziara** [comment]
Hi Nicolas,

The main issues was about understanding how parsing input files works in parallel. When you use ``soflec-mpi`` bodies are assigned to particular MPI ranks, while they are created, which means that *not all returned BODY objects are valid*. Users can check this by applying the [HERE](http://parmes.org/solfec/user/simulation.html#parallel-runtime) command, e.g.

```
bod = BODY(...)
if HERE(bod):
  print 'Body', bod.id, 'is on rank', RANK()
```

Solfec will store the first created body on rank 0, second created body on rank1, and so forth. For N MPI ranks the (N+1)th body will again be stored on rank 0. So, for example, the BODY object returned on rank 0 for the second created body will be only a *place holder* - when you call ``bod.center`` on it this will return ``None`` rather than a tuple of points. That was causing the problem in your input file.

In this case it was not necessary to use the HERE command. It was enough to change the order of declaring and using point data. Please see: [PUT_SPRING_2_sphere-RIG-v1.1.zip](https://github.com/tkoziara/solfec/files/1067417/PUT_SPRING_2_sphere-RIG-v1.1.zip)


*As another aspect of this* I also corrected one older bug in Solfec, due to which in the reports your were getting ``TypeError: 'body2' must be a tuple object`` instead of ``TypeError: 'point2' must be a tuple object``. Also I corrected another mistake - introduced recently - due to which this example was locking in parallel. **Please updated solfec sources and recompile.**

I hope this will now work OK:)
Tomek

**Comment by nicolasmecamas** [comment]
Hi Tomek,
I have updated the new version but it generated the same error as before. 
Did it work on your side this test?
Thank you in advance,
Nicolas

**Comment by tkoziara** [comment]
Hi Nicolas,
I zipped the unmodified file. Pleas try this one intead: [PUT_SPRING_2_sphere-RIG-v1.1.zip](https://github.com/tkoziara/solfec/files/1114571/PUT_SPRING_2_sphere-RIG-v1.1.zip)
Tomek
